#!/bin/bash
#configure this file for the main database parameters

# //////////////////////////////////////////////////////////////////////////////
# Set PATHS parameters
pth2dems=${HOME}/Map_project/dems
inputTopoL=${pth2dems}/ETOPO1_Bed_g_gmt4.grd
inputTopoB=${pth2dems}/ETOPO1_Bed_g_gmt4.grd
pth2logos=$HOME/Map_project/logos

# //////////////////////////////////////////////////////////////////////////////
# Set Network Style Ploting
gr_style="-St0.37c -W0.01c/0 -Gred"
sa_style="-St0.37c -W0.01c/0 -Ggreen"
ur_style="-St0.37c -W0.01c/0 -G0/0/160"
me_style="-St0.20c -W0.01c/0 -Gblack"
hp_style="-Sc0.24c -W0.01c/0 -Gred"

grcom_style="-St0.37c -W0.01c/0 -Gred"
grnoa_style="-St0.37c -W0.01c/0 -G153/76/0"
grcrl_style="-St0.37c -W0.01c/0 -Gblue"
greth_style="-St0.37c -W0.01c/0 -Gyellow"
# campaign site styles
#------------------------------------------------------
aegean_style="-St0.20c -W0.01c/0 -Gred"
centrgr_style="-Sc0.14c -W0.01c/0 -Gred"
corinth_style="-Sc0.10c -W0.01c/0 -Ggreen"
evia_style="-Sc0.08c -W0.01c/0 -G204/51/255"
grevena_style="-Sc0.10c -W0.01c/0 -Gbrown"
hellnet_style="-Sc0.12c -W0.01c/0 -G255/153/51"
ionian_style="-St0.18c -W0.01c/0 -G0/153/0"
roads_style="-Sc0.12c -W0.01c/0 -Gblack"
sing_style="-St0.18c -W0.01c/0 -Gblue"


# //////////////////////////////////////////////////////////////////////////////
# Pre-defined parameters for GMT
outfile=test.eps
out_jpg=test.jpg
landcpt=land_man.cpt
bathcpt=bath_man.cpt
maptitle=""

# //////////////////////////////////////////////////////////////////////////////
# Set FILE parameters
greece_sta=greece.sites
sant_sta=santorini.sites
uranus_sta=uranus.sites
metrica_sta=metrica.sites
hepos_sta=hepos21.sites
grecom_sta=comet.sites
grenoa_sta=noanet.sites
grecrl_sta=crlnet.sites
greeth_sta=HELLAS_ETH.txt

# campaign site styles
#------------------------------------------------------
aegean_sta=Aegean.txt
centrgr_sta=Central_Greece.txt
corinth_sta=Corinth_Gulf.txt
evia_sta=Evia.txt
grevena_sta=Grevena.txt
hellnet_sta=HELLNET.txt
ionian_sta=Ionian.txt
roads_sta=Roads.txt
sing_sta=SING.txt
