#!/bin/bash
#configure this file for the main database parameters

# //////////////////////////////////////////////////////////////////////////////
# Set PATHS parameters
pth2dems=${HOME}/Map_project/dems
inputTopoL=${pth2dems}/ETOPO1_Bed_g_gmt4.grd
inputTopoB=${pth2dems}/ETOPO1_Bed_g_gmt4.grd
pth2logos=$HOME/Map_project/logos

# //////////////////////////////////////////////////////////////////////////////
# Set Network Style Ploting
gr_style="-St0.37c -W0.01c/0 -Gred"
sa_style="-St0.37c -W0.01c/0 -Ggreen"
ur_style="-St0.37c -W0.01c/0 -G0/0/160"
me_style="-St0.20c -W0.01c/0 -Gblack"
hp_style="-Sc0.24c -W0.01c/0 -Gred"

grcom_style="-St0.37c -W0.01c/0 -Gred"
grnoa_style="-St0.37c -W0.01c/0 -G153/76/0"
grcrl_style="-St0.37c -W0.01c/0 -Gblue"


# //////////////////////////////////////////////////////////////////////////////
# Pre-defined parameters for GMT
outfile=test.eps
out_jpg=test.jpg
landcpt=land_man.cpt
bathcpt=bath_man.cpt
maptitle=""

# //////////////////////////////////////////////////////////////////////////////
# Set FILE parameters
greece_sta=greece.sites
sant_sta=santorini.sites
uranus_sta=uranus.sites
metrica_sta=metrica.sites
hepos_sta=hepos10.sites
grecom_sta=comet.sites
grenoa_sta=noanet.sites
grecrl_sta=crlnet.sites
